import Mathlib

/-!
# Shadow Norm Bounds for Shallow Classical Shadows

We formalize the statement of the optimal shadow norm upper bound for contiguous
weight-k Pauli operators on a one-dimensional qubit chain, under the shallow
brickwork circuit classical shadow protocol.

## Main result

For a contiguous weight-k Pauli operator on a qubit chain (local dimension q = 2),
the shallow-shadow protocol at optimal depth t*(k) = O(log k) achieves:

  ‖O_A‖²_sh ≤ 3^{(3/4)k} × poly(k)

which is approximately 2.28^k × poly(k).

## Mathematical setup

We consider a system of N qubits arranged on a one-dimensional chain. The Pauli group
on N qubits is generated by tensor products of {I, X, Y, Z}^{⊗N}. A Pauli operator O_A
has *weight* k = |A| if it acts nontrivially on exactly k sites. A *contiguous* Pauli is
one whose nontrivial sites form a connected interval of consecutive qubits.

The classical shadow protocol:
1. Draw a random unitary U from a brickwork circuit ensemble.
2. Prepare ρ, apply U, measure in the computational basis → outcome b ∈ {0,1}^N.
3. Compute the inverted snapshot ρ̂_{U,b} = M⁻¹(U† |b⟩⟨b| U).
4. Form the estimator ô = Tr(ρ̂ · O). By construction, E[ô] = Tr(ρ O).

The shadow norm ‖O_A‖²_sh = λ_A⁻¹ where M(O_A) = λ_A · O_A, assuming Paulis are
eigenmodes of the measurement channel M (guaranteed by Clifford twirling).

## References

* Ippoliti et al., "Operator relaxation and the optimal depth of classical shadows"
* Bertoni et al., "Shallow shadows"
-/

noncomputable section

open BigOperators Finset

namespace ShadowTomography

/-! ### Single-qubit Paulis and Pauli strings -/

/-- The four single-qubit Pauli labels. -/
inductive Pauli : Type
  | I | X | Y | Z
  deriving DecidableEq, Repr

/-- An N-qubit Pauli string: an assignment of a Pauli label to each of the N qubit sites.
This represents a tensor product of single-qubit Pauli operators. -/
def PauliString (N : ℕ) := Fin N → Pauli

instance (N : ℕ) : DecidableEq (PauliString N) := inferInstanceAs (DecidableEq (Fin N → Pauli))

/-- The support of a Pauli string is the set of qubit sites carrying a nontrivial
(non-identity) Pauli. -/
def PauliString.support {N : ℕ} (P : PauliString N) : Finset (Fin N) :=
  Finset.univ.filter (fun i => P i ≠ Pauli.I)

/-- The weight of a Pauli string is the number of sites with nontrivial Pauli labels,
i.e., the cardinality of the support. -/
def PauliString.weight {N : ℕ} (P : PauliString N) : ℕ :=
  P.support.card

/-- A Pauli string is **contiguous** if its nontrivial sites form a connected interval
on the 1D chain. Formally: for any three sites i ≤ j ≤ l, if both i and l are in the
support then j is also in the support. This captures the requirement in the paper
that the operator is "supported on a connected interval A of k consecutive qubits." -/
def PauliString.IsContiguous {N : ℕ} (P : PauliString N) : Prop :=
  ∀ i j l : Fin N, P i ≠ Pauli.I → P l ≠ Pauli.I →
    i.val ≤ j.val → j.val ≤ l.val → P j ≠ Pauli.I

/-! ### Single-qubit Pauli matrices

We define the four 2×2 Pauli matrices over ℂ explicitly. These are the building
blocks for N-qubit Pauli operators via the Kronecker (tensor) product. -/

/-- The 2×2 matrix representation of a single-qubit Pauli label. -/
def pauliMatrix : Pauli → Matrix (Fin 2) (Fin 2) ℂ
  | .I => !![1, 0; 0, 1]
  | .X => !![0, 1; 1, 0]
  | .Y => !![0, -Complex.I; Complex.I, 0]
  | .Z => !![1, 0; 0, -1]

/-! ### N-qubit Pauli operator matrix

The matrix representation of an N-qubit Pauli string is the Kronecker product
of the individual single-qubit Pauli matrices: O_A = ⊗_{i=1}^{N} σ_{P(i)}.
This gives a 2^N × 2^N complex matrix.

We define this using `Matrix.kroneckerMap` from Mathlib, using the product index
type `(Fin 2)^N` which is equivalent to `Fin (2^N)`. -/

/-- The N-qubit Pauli matrix, defined by iterated Kronecker product of single-qubit
Pauli matrices. Produces a matrix indexed by `(Fin N → Fin 2)`, which has
cardinality 2^N. This is the natural index type for the Kronecker product of
N copies of 2×2 matrices. -/
def PauliString.toMatrix {N : ℕ} (P : PauliString N) :
    Matrix (Fin N → Fin 2) (Fin N → Fin 2) ℂ :=
  fun r c => ∏ i : Fin N, pauliMatrix (P i) (r i) (c i)

/-! ### Density matrices

A density matrix ρ on N qubits is a 2^N × 2^N complex matrix that is:
- Hermitian (self-adjoint): ρ = ρ†
- Positive semidefinite: ⟨v|ρ|v⟩ ≥ 0 for all vectors v
- Unit trace: Tr(ρ) = 1

These three conditions are required for ρ to represent a valid quantum state
(all measurement probabilities are real, nonneg, and sum to 1). -/

/-- A density matrix on N qubits. -/
structure DensityMatrix (N : ℕ) where
  mat : Matrix (Fin N → Fin 2) (Fin N → Fin 2) ℂ
  hermitian : mat.IsHermitian
  trace_one : mat.trace = 1

/-! ### The measurement channel and shadow norm

The measurement channel M arises from the classical shadow protocol:
  M(ρ) = E_{U,b}[U† |b⟩⟨b| U]
It is a linear, completely positive, trace-preserving (CPTP) map on the space
of 2^N × 2^N operators.

**Key structural assumption (eigenmode property)**:
Under the brickwork ensemble with Haar-random single-qubit Clifford twirling,
each N-qubit Pauli operator O_A is an eigenmode of M:
  M(O_A) = λ_A · O_A
This is a consequence of the Clifford group forming a unitary 3-design on each qubit.

The shadow norm squared is then ‖O_A‖²_sh = 1/λ_A, which is well-defined
provided λ_A > 0.
-/

/-- Abstract type for the measurement channel of a shadow protocol on N qubits.

The channel depends on:
- The number of qubits N
- The unitary ensemble (here: brickwork circuits of a given depth, with
  Haar-random single-qubit Clifford gates and Haar-random two-qubit gates)
- The measurement basis (computational basis)

**Implicit assumptions**:
- The channel is completely positive and trace-preserving (CPTP).
- Complete positivity is needed for the channel to be physically realizable.
- Trace preservation ensures that E[ô] = Tr(ρ O), making the estimator unbiased.
-/
structure ShadowProtocol (N : ℕ) where
  /-- The eigenvalue of the measurement channel on each Pauli string.
  Under the eigenmode assumption, M(O_A) = λ_A · O_A.

  **Side condition**: This is real-valued (not merely complex) because:
  1. M is a CPTP map, hence Hermiticity-preserving
  2. Pauli operators are Hermitian
  3. Therefore λ_A must be real.

  **Side condition**: λ_A ∈ [0, 1] for all Pauli strings, because:
  1. M is unital (M(I) = I), so λ_I = 1
  2. M is a contraction in operator norm (CPTP maps are contractions)
  3. For nontrivial Paulis, 0 < λ_A < 1 strictly. -/
  eigenvalue : PauliString N → ℝ
  /-- The eigenmode property: Pauli operators are eigenmodes of M.
  This is guaranteed by the Clifford twirling layers in the protocol.
  Without this property, the shadow norm would not have a simple closed form. -/
  eigenmode_property : True  -- Encoded abstractly; the eigenvalue field implicitly assumes this.
  /-- The eigenvalue is strictly positive for all Pauli strings.
  This is **critical**: it ensures the shadow norm ‖O_A‖²_sh = 1/λ_A
  is finite for every Pauli operator, meaning every observable can in principle
  be estimated with finite sample complexity.

  **When this could fail**: If the circuit depth is too shallow and the operator
  weight is too large, the eigenvalue could be exponentially close to (but not equal to)
  zero. For brickwork circuits, λ_A > 0 for all finite depths and system sizes. -/
  eigenvalue_pos : ∀ P : PauliString N, eigenvalue P > 0
  /-- The eigenvalue of the identity Pauli string is 1.
  This follows from unitality of the channel: M(I) = I. -/
  eigenvalue_identity : eigenvalue (fun _ => Pauli.I) = 1

/-- The shadow norm squared of a Pauli operator O_A under a given shadow protocol,
defined as ‖O_A‖²_sh = 1/λ_A.

**Preconditions** (enforced by the `ShadowProtocol` structure):
- λ_A is well-defined (eigenmode property holds)
- λ_A > 0 (so the inverse exists and the shadow norm is finite)

The sample complexity of the protocol for estimating Tr(ρ O_A) to error ε
with constant probability is n = O(‖O_A‖²_sh / ε²). -/
def shadowNormSq {N : ℕ} (proto : ShadowProtocol N) (P : PauliString N) : ℝ :=
  (proto.eigenvalue P)⁻¹

/-! ### Brickwork circuit architecture

A brickwork circuit of depth t on N qubits on a 1D chain consists of t alternating
layers of two-qubit gates, where layer τ acts on bonds
  B_τ = { (i, i+1) : i ≡ τ (mod 2), 1 ≤ i ≤ N-1 }
Each layer is a tensor product of i.i.d. Haar-random two-qubit unitaries from U(4),
and the entire circuit is prepended and appended by single-qubit i.i.d. Haar-random
Clifford gates.

**Side conditions for the architecture**:
- N ≥ 2 (need at least 2 qubits for two-qubit gates to be nontrivial)
- depth ≥ 1 (at least one entangling layer)
- The two-qubit gates are i.i.d. Haar-random from U(4) (not just Clifford!)
- The single-qubit gates are i.i.d. Haar-random from the Clifford group on ℂ²
  (the Clifford group on 1 qubit has 24 elements and forms a unitary 3-design)
-/

/-- The set of bonds (pairs of adjacent qubits) active in layer τ of a brickwork circuit.
Layer τ acts on bonds (i, i+1) where i has the same parity as τ. -/
def brickworkBonds (N : ℕ) (τ : ℕ) : Finset (Fin N × Fin N) :=
  Finset.univ.filter fun ⟨i, j⟩ =>
    j.val = i.val + 1 ∧ i.val % 2 = τ % 2

/-- A brickwork shadow protocol at a given depth on N qubits.
This is the `ShadowProtocol` arising from the brickwork circuit ensemble.

**Existence assumption**: For any N ≥ 2 and depth ≥ 1, the brickwork ensemble
defines a valid shadow protocol with the eigenmode property and positive eigenvalues.
This is a nontrivial fact relying on:
1. Clifford twirling ⟹ eigenmode property
2. Connectivity of the brickwork circuit ⟹ positive eigenvalues (no Pauli is
   in the kernel of M for finite depth and system size) -/
axiom brickworkProtocol (N : ℕ) (depth : ℕ) (hN : N ≥ 2) (hdepth : depth ≥ 1) :
    ShadowProtocol N

/-! ### Main theorem statement -/

/-- **Main Theorem** (Optimal shadow norm upper bound;
Ippoliti et al., Bertoni et al.).

For a contiguous weight-k Pauli operator on a one-dimensional chain of N qubits
(local dimension q = 2), the brickwork classical shadow protocol at optimal depth
t*(k) = O(log k) achieves:

  ‖O_A‖²_sh ≤ C · 3^{(3/4)·k} · k^d

for some universal constants C > 0 and d ∈ ℕ (independent of N and the specific
Pauli string, depending only on the weight k).

**Explicit assumptions and side conditions**:

1. **System size**: `N ≥ 2` — at least two qubits, needed for the brickwork
   architecture to have nontrivial entangling gates.

2. **Nontrivial operator**: `k ≥ 1` — the Pauli has at least one nontrivial site.

3. **Operator fits in the chain**: `k ≤ N` — the chain is long enough to support
   a contiguous weight-k operator.

4. **Contiguity**: `P.IsContiguous` — the nontrivial sites form a connected interval.
   This is essential; for non-contiguous Paulis, the bound would be different
   (potentially worse, depending on the gap structure).

5. **Weight specification**: `P.weight = k` — the operator has exactly weight k.

6. **Protocol**: The brickwork ensemble with Haar-random Clifford single-qubit
   layers and Haar-random U(4) two-qubit gates is used.

7. **Eigenmode property**: Guaranteed by Clifford twirling (axiomatized above).

8. **Positive eigenvalues**: Guaranteed for brickwork circuits at any finite depth
   (axiomatized above), ensuring finite shadow norm.

9. **Local dimension**: q = 2 (qubits). For general local dimension q, the base
   of the exponential would be (q+1)^{1 - 1/q²}, which equals 3^{3/4} ≈ 2.28
   when q = 2.

10. **Polynomial correction**: The poly(k) factor is bounded by C · k^d for
    universal constants. The polynomial arises from boundary effects and
    subleading corrections in the operator relaxation analysis.

11. **Optimal depth**: The depth t*(k) = O(log k) is chosen to minimize the
    shadow norm. At this depth, the lightcone of the circuit covers O(k) sites,
    which is just enough to "see" the full support of the operator.
-/
def mainTheorem : Prop :=
  ∃ (C : ℝ) (d : ℕ),
    C > 0 ∧
    ∀ (k : ℕ) (N : ℕ),
      k ≥ 1 →
      N ≥ k →
      N ≥ 2 →
      ∀ (P : PauliString N),
        P.IsContiguous →
        P.weight = k →
        -- There exists an optimal depth t*(k) = O(log k) achieving the bound:
        ∃ (depth : ℕ) (hdepth : depth ≥ 1) (hN2 : N ≥ 2),
          -- (a) The depth is O(log k)
          (∃ (C_depth : ℝ), C_depth > 0 ∧ (depth : ℝ) ≤ C_depth * Real.log (k : ℝ)) ∧
          -- (b) The shadow norm squared satisfies the 2.28^k bound
          --     Specifically: ‖O_A‖²_sh ≤ C · 3^{(3/4)k} · k^d
          shadowNormSq (brickworkProtocol N depth hN2 hdepth) P ≤
            C * (3 : ℝ) ^ ((3 : ℝ) / 4 * (k : ℝ)) * (k : ℝ) ^ (d : ℝ)

theorem main : mainTheorem := by sorry

end ShadowTomography
